# -*- coding: utf-8 -*-
"""deploy_agent_with_fastapi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16W1vJ0dhewgwjHJDokLiu10d6i5Yu_09
"""

!pip install -q openai fastapi uvicorn pyngrok nest_asyncio

from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI
from getpass import getpass

import nest_asyncio
from pyngrok import ngrok
import uvicorn

api_key = getpass("Enter OpenAI API Key: ")

client = OpenAI(api_key=api_key)

def ask_agent(question):

    response = client.responses.create(

        model="gpt-4.1-mini",

        instructions="""
        You are an AI Engineering assistant.
        Keep answers concise and beginner friendly.
        """,

        input=question
    )

    return response.output_text

app = FastAPI()

class Query(BaseModel):
    question: str

@app.post("/agent")
def chat(request: Query):

    answer = ask_agent(request.question)

    return {
        "question": request.question,
        "answer": answer
    }

import nest_asyncio
import threading
import uvicorn
from pyngrok import ngrok

# Allow nested event loops
nest_asyncio.apply()

# Set your ngrok authtoken
ngrok.set_auth_token("your_ng_rok_auth_token")

# Function to run FastAPI
def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

# Start FastAPI in a background thread
threading.Thread(target=run_server, daemon=True).start()

# Create the public tunnel
public_url = ngrok.connect(8000)

print("Public URL:", public_url)

