# -*- coding: utf-8 -*-
"""invoke_agent_fast_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T-NeOZjIQYC5ZMWKenDgboJuJF8XSIm
"""

import requests

url = "https://0e19-34-21-183-179.ngrok-free.app/agent"

payload = {
    "question": "Explain Agentic AI in simple terms."
}

response = requests.post(url, json=payload)

print(response.json())

