# -*- coding: utf-8 -*-
"""agent-with-memory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPYESqLhLjxdaKW70KOTK_pbQqqFmKZL
"""

!pip install -q openai

from openai import OpenAI
from getpass import getpass

api_key = getpass("OpenAI API Key: ")

client = OpenAI(api_key=api_key)

messages = []

system_prompt = """
You are an AI Engineering instructor.
Answer simply and clearly.
"""

def chat(question):

    messages.append({
        "role":"user",
        "content":question
    })

    response = client.responses.create(

        model="gpt-4.1-mini",

        instructions=system_prompt,

        input=messages

    )

    answer = response.output_text

    messages.append({
        "role":"assistant",
        "content":answer
    })

    return answer

print(chat("Who is Andrew Ng?"))

print(chat("Where does he teach?"))

print(chat("What courses is he famous for?"))

