# -*- coding: utf-8 -*-
"""multi_turn_ai_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4KqRST8vVFVSrpyQlEbCH67GbFTNLKD
"""

!pip install -q openai

from openai import OpenAI
from getpass import getpass

api_key = getpass("Enter OpenAI API Key: ")

client = OpenAI(api_key=api_key)

messages = []

system_prompt = """
You are a helpful AI assistant.
Answer clearly and concisely.
"""

def chatbot(question):

    messages.append({
        "role":"user",
        "content":question
    })

    response = client.responses.create(

        model="gpt-4.1-mini",

        instructions=system_prompt,

        input=messages

    )

    answer = response.output_text

    messages.append({
        "role":"assistant",
        "content":answer
    })

    return answer

while True:

    question = input("You : ")

    if question.lower() == "exit":
        break

    answer = chatbot(question)

    print("\nAgent :", answer)
    print()

