# -*- coding: utf-8 -*-
"""tool_calling_ai_agent_with_openai_sdk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BANeXA-ksK3mNosfZfNtzxu0-ptxSx5g
"""

!pip install -q openai

from openai import OpenAI
from getpass import getpass

api_key = getpass("Enter OpenAI API Key: ")

client = OpenAI(api_key=api_key)

def get_weather(city):

    weather_data = {
        "New York": "Sunny, 27 degrees Celsius",
        "London": "Cloudy, 18 degrees Celsius",
        "Tokyo": "Rainy, 21 degrees Celsius"
    }

    return weather_data.get(city, "Weather data not available")

response = client.responses.create(
    model="gpt-4.1-mini",
    input="What is the weather in New York?"
)

print(response.output_text)

city = "New York"

weather = get_weather(city)

print(weather)

weather = get_weather("New York")

response = client.responses.create(
    model="gpt-4.1-mini",
    input=f"""
The weather in New York is:

{weather}

Generate a friendly response for the user.
"""
)

print(response.output_text)

def weather_agent(city):

    weather = get_weather(city)

    response = client.responses.create(
        model="gpt-4.1-mini",
        instructions="""
        You are a helpful weather assistant.
        Explain the weather in a friendly way.
        """,
        input=f"The weather in {city} is {weather}"
    )

    return response.output_text


print(weather_agent("New York"))

