# -*- coding: utf-8 -*-
"""openai_tracing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1abBfkooOLhTjqEyfLPbV3y7_fYisoj
"""

!pip install -q openai-agents

from agents import Agent, Runner
from getpass import getpass
import os


os.environ["OPENAI_API_KEY"] = getpass("Enter OpenAI API Key: ")

agent = Agent(

    name="History Tutor",

    instructions="""
    You answer history questions clearly and concisely.
    """,

    model="gpt-5.5"

)

result = await Runner.run(

    agent,

    "When did the Roman Empire fall?"

)

print(result.final_output)

science_agent = Agent(

    name="Science Tutor",

    instructions="""
    Explain science concepts simply.
    Use examples whenever possible.
    """,

    model="gpt-5.5"

)

result = await Runner.run(

    science_agent,

    "Why is the sky blue?"

)

print(result.final_output)

