# -*- coding: utf-8 -*-
"""ai_agent_with_openAI_SDK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L63__39bq6jIwwrT_OkCHmxn0SLOKugW
"""

!pip install -q openai

from openai import OpenAI

from getpass import getpass

api_key = getpass("Enter your OpenAI API Key: ")

client = OpenAI(api_key=api_key)

response = client.responses.create(
    model="gpt-4.1-mini",
    input="What is an AI Agent?"
)

print(response.output_text)

response = client.responses.create(
    model="gpt-4.1-mini",

    instructions="""
    You are an AI Engineering instructor.
    Explain concepts simply.
    Keep answers under 100 words.
    """,

    input="Explain MLOps."
)

print(response.output_text)

def ask_agent(question):

    response = client.responses.create(
        model="gpt-4.1-mini",

        instructions="""
        You are an AI Engineering assistant.
        Explain clearly.
        Use simple language.
        Keep answers concise.
        """,

        input=question
    )

    return response.output_text

print(ask_agent("What is Deep Learning?"))

print(ask_agent("Explain TensorFlow Serving"))

print(ask_agent("What is MLOps?"))

def ask_stock_agent(question):

    response = client.responses.create(
        model="gpt-4.1-mini",

        instructions="""
        You are an experienced stock market analyst.
        Explain everything in simple language.
        """,

        input=question
    )

    return response.output_text

print(ask_stock_agent("Should investors diversify their portfolio?"))

