# -*- coding: utf-8 -*-
"""multi_agent_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lI_Q-BzUjs-JxEhn7hT2TBDVHF8a1gLs
"""

!pip install -q openai-agents yfinance resend schedule

import os
from getpass import getpass

os.environ["OPENAI_API_KEY"] = getpass("Enter OpenAI API Key: ")
os.environ["RESEND_API_KEY"] = getpass("Enter Resend API Key: ")

import yfinance as yf

def get_stock_info(ticker):

    stock = yf.Ticker(ticker)

    info = stock.history(period="2d")

    current = info["Close"].iloc[-1]

    previous = info["Close"].iloc[-2]

    change = (current - previous) / previous * 100

    return {

        "ticker": ticker,

        "current": current,

        "previous": previous,

        "change": change

    }

from agents import Agent

price_agent = Agent(

    name="Price Analyst",

    instructions="""
    Analyze stock price movements.
    Explain whether the movement is significant.
    Keep your answer under 50 words.
    """,

    model="gpt-5.5"

)

news_agent = Agent(

    name="News Researcher",

    instructions="""
    Search for possible reasons behind today's stock movement.
    Summarize recent news in under 75 words.
    """,

    model="gpt-5.5"

)

summary_agent = Agent(

    name="Investment Summary",

    instructions="""
    Combine multiple analyses into a professional email.

    Keep the response under 120 words.

    """,

    model="gpt-5.5"

)

from agents import Runner

stock = get_stock_info("MSFT")

price_prompt = f"""
Ticker: {stock['ticker']}

Current Price: {stock['current']}

Previous Close: {stock['previous']}

Percentage Change: {stock['change']:.2f}%

Explain this price movement.
"""

price_result = await Runner.run(
    price_agent,
    price_prompt
)

print(price_result.final_output)

news_prompt = f"""
The stock {stock['ticker']} moved {stock['change']:.2f}% today.

Use your knowledge and reasoning to explain possible reasons
behind this movement.
"""

news_result = await Runner.run(

    news_agent,

    news_prompt

)

print(news_result.final_output)

summary_prompt = f"""

Price Analysis

----------------

{price_result.final_output}

News Analysis

----------------

{news_result.final_output}

Create a professional investment summary suitable for an email.
"""

summary_result = await Runner.run(

    summary_agent,

    summary_prompt

)

print(summary_result.final_output)

def send_email(subject, body):

    response = resend.Emails.send({

        "from": "onboarding@resend.dev",

        "to": "youremail@gmail.com",

        "subject": subject,

        "html": f"""
        <html>

        <body style="font-family:Arial">

        <h2>📈 AI Stock Alert</h2>

        <hr>

        <p>{body}</p>

        </body>

        </html>
        """

    })

    return response

subject = f"🚨 {stock['ticker']} Alert ({stock['change']:.2f}%)"

response = send_email(

    subject,

    summary_result.final_output

)

print(response)

