# -*- coding: utf-8 -*-
"""resend-email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGqImAl-2fwPQJX-ZpNuVMbix8hyKFLv
"""

!pip install -q resend

import os
from getpass import getpass
import resend

# Enter your Resend API Key
os.environ["RESEND_API_KEY"] = getpass("Enter Resend API Key: ")

resend.api_key = os.environ["RESEND_API_KEY"]

response = resend.Emails.send({

    "from": "onboarding@resend.dev",

    "to": "youremail@gmail.com",

    "subject": "Hello from Resend!",

    "html": """
    <h2>🎉 Congratulations!</h2>

    <p>This is my second email.</p>

    <p>Testing before building agents.</p>
    """

})

print(response)

